STAGE: ${opt:stage, self:provider.stage}
SLACK_TOKEN: ${ssm:SLACK_TOKEN}
SLACK_ID: ${ssm:SLACK_ID}
SLACK_ID_DEBUG: ${ssm:SLACK_ID_DEBUG}
SLACK_ID_ERROR: ${ssm:SLACK_ID_ERROR}
CHROME_EXECUTABLE_PATH: "/opt/python/bin/chromedriver"
MYSQL_HOST_STG: ${ssm:MYSQL_HOST_STG}
MYSQL_USER_STG: ${ssm:MYSQL_USER_STG}
MYSQL_ROOT_PASSWORD_STG: ${ssm:MYSQL_ROOT_PASSWORD_STG}
MYSQL_PORT_STG: ${ssm:MYSQL_PORT_STG}
MYSQL_HOST_PROD: ${ssm:MYSQL_HOST_PROD}
MYSQL_USER_PROD: ${ssm:MYSQL_USER_PROD}
MYSQL_ROOT_PASSWORD_PROD: ${ssm:MYSQL_ROOT_PASSWORD_PROD}
MYSQL_PORT_PROD: ${ssm:MYSQL_PORT_PROD}
